//
// Created by lucas on 7/1/25.
//

#ifndef WORLD_HPP
#define WORLD_HPP

#include <unordered_map>
#include <cmath>
#include <algorithm>
#include <unordered_set>
#include <memory>
#include <string>

#include <mutex>
#include <future>
#include <fstream>
#include <filesystem>
#include <optional>
#include <cstring>
#include <zstd.h>

#include "TerrainParams.hpp"
#include "Protocol.hpp"
#include "PlayerInfo.hpp"
#include "CommonWorld.hpp"
#include "LiquidsManager.hpp"

static constexpr int MAXIMUM_NUMBER_OF_CHUNKS_SENT_PER_TICK = 20;
static constexpr int REGION_SIZE = 32;
static constexpr int MAX_RADIUS = 32;
static constexpr int RADIUS_OF_REGIONS_TO_KEEP = 2;
static constexpr ChunkPos INVALID_CHUNK = {std::numeric_limits<int>::min(), std::numeric_limits<int>::min()};
static constexpr bool SAVES_ACTIVE = false;

struct RegionFileMetadata {
    char magic[4] = {'R','G','N','1'};
    std::uint32_t version = 1;
    std::uint32_t regionSize = REGION_SIZE;
};

struct ChunkEntry {
	std::uint32_t X;
	std::uint32_t Z;
    std::uint32_t offset;
    std::uint32_t size;
};

struct SkyTimeState {
	// Sky time (server-authoritative)
	float   skyTimeOffset  = 0.5f;
	float   sunYawDeg      = 45.0f;
	float   sunPauseTimer  = 0.0f;
	float   sunStepTimer   = 0.0f;
	bool    sunStepping    = false;
	bool    skyTimePaused  = false;
	uint8_t skyMode        = 1;     // 0 = Skyrim, 1 = Smooth
	float   skyTimeSpeed   = 0.05f;
};

class World final : public CommonWorld<ChunkGeneration>
{
    TerrainGenerationParams terrainParams;

	inline int floorDiv(int value, int divisor) {
		if (value >= 0) return value / divisor;
		return (value - divisor + 1) / divisor; // floor division for negatives
	}

	// Set of chunks currently being generated by async tasks.  Prevents
	// scheduling duplicate generation for the same chunk.
	// std::unordered_set<ChunkPos> generatingChunks;
    // Pending futures representing asynchronous chunk generation tasks.
    // std::vector<std::future<std::pair<ChunkPos, std::shared_ptr<ChunkGeneration>>>> generationFutures;

	std::unordered_set<ChunkPos> plannedChunks;
	std::unordered_map<ChunkPos, std::future<std::shared_ptr<ChunkGeneration>>> chunkJobs;
	std::vector<ChunkPos> CircularGrid;

    mutable std::mutex chunkMutex;
	bool outOfMemory = false;

    // Maximum number of chunk generation tasks that can be running at the
    // same time.  Limiting concurrency prevents CPU oversubscription and
    // reduces frame drops when many chunks need to be generated.  This
    // value can be tuned based on the number of available CPU cores.
    std::size_t maxConcurrentGeneration = 20;
	std::size_t maxConcurrentGenerationPerPlayer = 4;

	static constexpr size_t MAX_DUMP_PIXELS = 4096ULL * 4096ULL; // ~64MB/channel

	void linkNeighbors(int chunkX, int chunkZ, std::shared_ptr<ChunkGeneration> &chunk); // TODO : consider moving to shared?

	std::unordered_set<ChunkPos> loadedRegions;
	void saveRegion(int regionX, int regionZ);
	void loadRegion(int regionX, int regionZ);
	std::string getRegionFilename(int regionX, int regionZ) const;
	void unloadChunksInRegion(int regionX, int regionZ);
	std::string regionDirName;

	ChunkPos findNextChunk(CPlayerInfo& player);
	void unloadPlayerKnownChunks(CPlayerInfo &player);
	std::vector<ChunkPos> buildCircularOffsets(int radius);

	SkyTimeState skyTimeState;

	public:
		World();
		World(int seed);

		~World();

		int amountOfChunksSentThisTick = 0;
		s_liquidsManager liquidsManager;
		std::vector<NetEntityMove> deletedEntitiesPkts; //Not very pretty. Should be entities and not packets but then types are a bit bothering to keep.
		std::vector<std::pair<sockaddr_in, NetInventory>> pickedUpItems;
		std::vector<ChunkPos> rdyChunks;
		std::unordered_map<int, std::unordered_set<ChunkPos>> PlayerKnownChunks;

		void dumpHeightmap(const TerrainGenerationParams& params, int centerChunkX, int centerChunkZ, int chunksX, int chunksZ, int downsample, int image) const;
		void dumpBiomeMap(const TerrainGenerationParams& params, int centerChunkX, int centerChunkZ, int chunksX, int chunksZ, int downsample);

		std::vector<s_waterPath> findShortestWaterPath(const glm::ivec3 &initialBlockPos);
		std::vector<std::shared_ptr<s_liquid>> waterFlowTowardsShortestPath(const glm::ivec3 &initialBlockPos, const std::shared_ptr<s_liquid> &liquid, const std::vector<s_waterPath> &paths);

		void updateRdyChunks();
		void updatePlayerRdyChunks(CPlayerInfo &player);
		void updateVisibleChunks(CPlayerInfo &player);
		void updateRegionStreaming(std::vector<CPlayerInfo> &players);

		void updateLiquids();

		// Get or set the maximum number of chunk generation tasks that can run
		// simultaneously.  Lower values reduce CPU spikes at the cost of slower
		// world loading.  Must be at least 1.
		// std::size_t getMaxConcurrentGeneration() const { return maxConcurrentGeneration; }
		// void setMaxConcurrentGeneration(std::size_t n) { maxConcurrentGeneration = std::max<std::size_t>(1, n); }

		void saveRegionsOnExit();
		// Terrain params for ImGui
		TerrainGenerationParams& getTerrainParams() { return terrainParams;}

		// Set all terrain parameters at once (used for syncing from client)
		void setTerrainParams(const TerrainGenerationParams& p) { terrainParams = p; }

		// void setCandidates(std::vector<std::tuple<int, int, float, float>> &candidates, const CPlayerInfo &player);
		// void updatePlannedChunks(CPlayerInfo &player);

		std::vector<std::pair<glm::ivec3, BlockType>> updatedBlocks;

		//returns true if item has been placed
		bool processPlayerMouseInputs(CPlayerInfo &player, const NetPlayerMouseInputs &pkt, int32_t clientTick);
		void updateEntitiesPosition(const std::vector<CPlayerInfo> &players, int32_t clientTick);	

		bool setBlockWorld(glm::ivec3 globalCoords, std::optional<glm::ivec3> faceNormal, BlockType type) override;
		void setWaterWorld(glm::ivec3 globalCoords, std::optional<glm::ivec3> faceNormal, BlockType type);

		// Carves a sphere of blocks to air and deals falloff damage + knockback to every
		// LivingEntity inside. `source` (if non-null) is flagged diedByExplosion on hit so
		// the server skips its fall-over animation. knockH/knockV are peak impulses at
		// center, linearly falling off to 0 at radius.
		void explodeAt(const glm::vec3 &center, float radius, float maxDamage,
		               float knockH, float knockV, LivingEntity *source);

		void advanceSkyTime();

		void setSkyTime(const SkyTimeState &newState);

		const SkyTimeState& getSkyTimeState() const { return skyTimeState; };
};

#endif //WORLD_HPP